### ISSUE TITLE
Upgrade from 1.7.9 to 1.9.3

### ISSUE THREAD

**Issue by todoesverso** [Azure/acs-engine#2385]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
Version: v0.13.1
GitCommit: 797dd91
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s 1.7.9 upgraded to 1.8.8

**What happened**:
I had _1.7.9_ deployed from a clean acs-engine deploy using the _example/kubernetes.json_.
Then I upgraded using `acs-engine upgrade --upgrade-version 1.8.8`, which corretly upgraded my cluster.
Intermediately after that I run `acs-engine upgrade --upgrade-version 1.9.3` and got a failure

`FATA[0007] version 1.9.3 is not supported 
`
**What you expected to happen**:
T obe able to upgrade k8s to 1.9.3.

**How to reproduce it** (as minimally and precisely as possible):
`acs-engine deploy --api-model example/kubernetes.json `
`acs-engine upgrade --upgrade-version 1.8.8 --deployment-dir _output/test`
`acs-engine upgrade --upgrade-version 1.9.3 --deployment-dir _output/test`

**Anything else we need to know**:
Not sure how things supposed to work, but what i see is that the `apimodel.json` file is not updated

```
$ grep -r 1.7.9 *
_output/test/azuredeploy.parameters.json:      "value": "k8s-gcrio.azureedge.net/hyperkube-amd64:v1.7.9"
_output/test/azuredeploy.json:    "orchestratorNameVersionTag": "Kubernetes:1.7.9",
_output/test/apimodel.json:      "orchestratorVersion": "1.7.9",
```

**Comment by CecileRobertMichon** [comment]
@todoesverso this is a known issue that was fixed with #2306. Right now the issue is fixed in master but the fix was not included in a release yet. Are you able to build from master?

**Comment by todoesverso** [comment]
It did worked although I still see 1.7.9 in some files, is that correct:

 `acs-engine-test$ grep -r 1.7.9 *
_output/victor-acs-tests-5a9d5ec6/azuredeploy.parameters.json:      "value": "k8s-gcrio.azureedge.net/hyperkube-amd64:v1.7.9"
_output/victor-acs-tests-5a9d5ec6/azuredeploy.json:    "orchestratorNameVersionTag": "Kubernetes:1.7.9",
acs-engine-test$ grep -r 1.8.8 *
_output/victor-acs-tests-5a9d5ec6/apimodel.json:      "orchestratorVersion": "1.8.8",
`

**Comment by CecileRobertMichon** [comment]
As long as your `apimodel.json` file has the up-to-date version, I believe you should be able to perform successive upgrades. The `azuredeploy.parameters.json` and `azuredeploy,json` files were used for your original deployment.
