### ISSUE TITLE
kubectl-extract service cannot be run successfully.

### ISSUE THREAD

**Issue by wangtt03** [Azure/acs-engine#348]

**Comment by wangtt03** [comment]
this PR should fix the problem: https://github.com/Azure/acs-engine/pull/347

**Comment by wangtt03** [comment]
@anhowe @colemickens could you please assign the issue to me because i am fixing this issue. Thanks!

**Comment by colemickens** [comment]
@wangtt03 This is not resolved, as per other threads. It is still flaky. Please take a look at this.

**Comment by colemickens** [comment]
@wangtt03 please note someone reported here that it is still happening even after they pulled latest: https://github.com/Azure/acs-engine/pull/151#issuecomment-284018359

**Comment by mfaizanse** [comment]
@wangtt03 I told you 2 hours ago that I tried the deployment and the kubectl run successfully but now I have redeployed win+k8s cluster to "West Europe" with VM class Standard_A4_v2 for master and Standard_DS3_v2 for agents using a different subscription, and the kubectl extract failed again.

Can I get you on slack?

cc: @colemickens

**Comment by mfaizanse** [comment]
@wangtt03 I redeployed the same template again and now the kubectl is working. i think the deployment is not stable, it's working sometime and sometime not. :)

**Comment by wangtt03** [comment]
@mfaizanse are you deploying a kubernetes cluster on windows?

**Comment by mfaizanse** [comment]
@wangtt03 yes I am deploying win + k8s cluster.

**Comment by wangtt03** [comment]
@mfaizanse Could you please provide more info about `sudo journalctl -u kubectl-extract`? Or could you please share me a copy of `/var/log/syslog` and `/var/log/azure/clusterProvision.log` on which the kubectl is missing?

**Comment by mfaizanse** [comment]
@wangtt03 As i have said in my above comment that in the new deployment the kubectl extraction was successful. And I have deleted the older cluster in which the kubectl extract failed. I will try to get these logs if my any other deployment failed.

**Comment by wangtt03** [comment]
@colemickens for windows kubernetes setup I think the powershell script `kuberneteswindowssetup.ps1` do the extraction job, right?

**Comment by colemickens** [comment]
No. On the Windows cluster, there is still a normal Linux master. The
Windows part should have no bearing on this problem.

**Comment by wangtt03** [comment]
OK. I see. I will fix the bug:)

**Comment by wangtt03** [comment]
@mfaizanse https://github.com/Azure/acs-engine/pull/364/commits/bab4c1f6e3deca35715f1267e1620431f8866c6e This fix should solve the problem. Could you please have a try? Thanks!😊

**Comment by wangtt03** [comment]
@colemickens This commit is auto appended in my another PR https://github.com/Azure/acs-engine/pull/364 Could you please review it? Thanks!

**Comment by wangtt03** [comment]
I guess the root cause is still the timing issue when systemd restart docker. From the syslog the `ensureDocker` function is satisfied and `ensureKubelet`, `extractKubectl` is running. At this time the  `systemctl restart docker` in the cloud-init runs which interrupts the process of kubectl-extract. I removed this statement from the cloud-init and did several deployments and all of them successful. Hope this fix can solve the problem:)

**Comment by anhowe** [comment]
completed in https://github.com/Azure/acs-engine/issues/344
