### ISSUE TITLE
k8s: Internal cluster requests via services does not work to windows nodes

### ISSUE THREAD

**Issue by ajorkowski** [Azure/acs-engine#572]
This is the last issue I have been facing to migrate some of our old services to kubernetes. We have 2 deployments that target windows nodes, and 2 that target linux. On top of that we are using an nginx ingress to direct traffic using the host headers. I am using a self-contained cluster - no custom/extended VNETs etc.

Windows:
- kalix-web-testing (with service, no LB). Mapped to test.kalixhealth.com
- kalix-worker-testing (no service)

Linux:
- kalix-ui-staging (with service, no LB). Mapped to testapp.kalixhealth.com
- kalix-websockets-staging (with service, no LB). Mapped to test-ws.kalix.co
- nginx-ingress-controller (with service that is LB). All external DNS servers are mapped to this service ip

The application works perfectly when you hit it from the outside, however some problems come up when the windows based pods try to access another windows based pod. Specifically when I try to curl from inside the pod I get an `Unable to connect to the remote server`.

Here are some examples from inside a `kalix-worker-testing` pod where I need to hit the `kalix-web-testing` pod.

***First Attempt - External DNS***
The first thing I tried was to keep the application the same and just use the external DNS name (I have checked nslookup and made sure that resolves correctly, also the same thing happens using the IP directly):

```
PS C:\app> curl test.kalixhealth.com
curl : Unable to connect to the remote server
```

It seems there have been a number of issues relating to this specific use case (I noticed that ping doesn't even work in this case as well) so I wasn't too surprised that this didn't work. I can also confirm that there are no logs in the nginx ingress controller for this request.

***Second Attempt - Internal DNS using service***
```
PS C:\app> curl kalix-web-testing.default.svc.cluster.local -UseBasicParsing
curl : Unable to connect to the remote server
```

This is a bit more interesting as I am able to ping the associated IP address and get a reply. Also the same command works if I try to ping one of the linux pods:

```
PS C:\app> curl kalix-ui-staging.default.svc.cluster.local -UseBasicParsing


StatusCode        : 200
StatusDescription : OK
``` 

***Third Attempt - Internal Proxy through nginx ingress***

I am able to hit the nginx ingress controller from the windows node, and it works externally so I thought I might be tricky and try to make use of the reverse proxy.

```
PS C:\app> curl nginx-ingress-lb.default.svc.cluster.local
curl : default backend - 404
```

Yay! However if I try to set the host so that it would redirect back to the windows box (something that works externally) it has the same problem.

```
PS C:\app> curl nginx-ingress-lb.default.svc.cluster.local -headers @{ "HOST" = "test.kalixhealth.com" }
curl : Unable to connect to the remote server
```

Although to be fair it doesn't work for a linux-based pod either

```
PS C:\app> curl nginx-ingress-lb.default.svc.cluster.local -headers @{ "HOST" = "testapp.kalixhealth.com" }
curl : Unable to connect to the remote server
```

NOTE: I can actually see log lines in the nginx ingress controller logs, so these requests do seem to be reach nginx and it does look like it is detecting the correct mapping (it shows the associated service). After that it looks like there is no response.

***Fourth Attempt - Direct Access using Pod IP***
I'm not sure this is supposed to work, but I was getting a bit desperate. I grabbed the IP for the pod directly from the dashboard and tried to curl using that.

```
PS C:\app> ping 10.244.2.130

Pinging 10.244.2.130 with 32 bytes of data:
Reply from 10.244.2.130: bytes=32 time<1ms TTL=126
Reply from 10.244.2.130: bytes=32 time=1ms TTL=126
Reply from 10.244.2.130: bytes=32 time<1ms TTL=126

Ping statistics for 10.244.2.130:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms

PS C:\app> curl 10.244.2.130
curl : Unable to connect to the remote server
```
***Linux***
If I go into a linux based pod all of the above methods seem to work

```
root@kalix-ui-staging-2182043284-zxfz4:/app# curl test.kalixhealth.com
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

<43284-zxfz4:/app# curl kalix-web-testing.default.svc.cluster.local
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/login?ReturnUrl=%2F">here</a>.</h2>
</body></html>

root@kalix-ui-staging-2182043284-zxfz4:/app# curl nginx-ingress-lb.default.svc.cluster.local --header "HOST: test.kalixhealth.com"
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

root@kalix-ui-staging-2182043284-zxfz4:/app# curl 10.244.2.130
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/login?ReturnUrl=%2F">here</a>.</h2>
</body></html>
```

***In the Node***
If I RDP into one of the windows nodes then method 1 and 4 works. For 2/3 the DNS could not be resolved.

***Conclusion***
I can't seem to work out any way to do pod -> pod communications between windows based pods. Is this supposed to be possible? I'm happy to do more investigating if anyone has any pointers.

**Comment by anhowe** [comment]
Was this just pod to pod between pods on the same windows machine? or across windows machines?  Both scenarios should work.  Also to help us repro, are you using the latest acs-engine, and what version of kubernetes are you using?

**Comment by ajorkowski** [comment]
Sorry about not including the important information! I am not using the absolute latest version of acs, but a fairly recent version just after the winnat pull request (#520 d852aba). I didn't update because it didn't look like there was anything major that came out after that. Using kubernetes 1.6.2.

In my test case the pods were in different nodes. However I went in just now and kept deleting the worker pod until both windows pods ended up in the same node and then re-tried all the attempts. Unfortunately it looks like it is still a problem even when they are on the same node.

**Comment by JiangtianLi** [comment]
@ajorkowski A couple of things to check: 
1. What is the output of `ipconfig /all` in your Windows POD? There was an issue with DNS server configuration and was fixed recently. 
2. Did you RDP to Windows node? If so, what is the output of `netsh advf show allprofiles`? Specifically is public profile state ON?
3. Besides `nslookup`, can you try `Resolve-DnsName`. There was an issue with kube-proxy for different DNS clients so use `Resolve-DnsName` to make sure DNS query is fine. It was also fixed in 1.5.3 this Monday.

**Comment by ajorkowski** [comment]
Thanks @JiangtianLi. 

I was having DNS issues as a separate problem as per #558 which is somewhat mitigated now. With all of these examples I also resolved the ip (using `nslookup`) and executed the same commands, with the same results. I did this knowing that the DNS might have been a problem but I put the full names in this bug report to illustrate the structure better.

I will spin up the cluster later today and do some more testing and get some outputs for you. I'll get latest from master - also do you recommend that I keep using 1.6.2 or fallback to 1.5.3?

**Comment by JiangtianLi** [comment]
@ajorkowski Thanks for trying out. 1.5.3 has been tested more with acs-engine than 1.6.2. However, if you notice the discrepancy between 1.6.2 and 1.5.3, please let me know and I will fix ASAP (I just fixed one issue in 1.6.2 yesterday).

**Comment by ajorkowski** [comment]
Alright, I've gotten the latest commit from master (a2e71c163ff30ae01940fbe7eff072901bcc582e) spun up a new cluster (kubernetes 1.6.2) and still getting the same issue:

```
PS C:\app> nslookup kalix-web-testing.default.svc.cluster.local
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.0.0.10

Name:    kalix-web-testing.default.svc.cluster.local
Address:  10.0.236.124

PS C:\app> Resolve-DnsName kalix-web-testing.default.svc.cluster.local

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
kalix-web-testing.default.svc.cluster.local    A      7     Answer     10.0.236.124


PS C:\app> ping kalix-web-testing.default.svc.cluster.local

Pinging kalix-web-testing.default.svc.cluster.local [10.0.236.124] with 32 bytes of data:
Reply from 10.0.236.124: bytes=32 time<1ms TTL=128
...

PS C:\app> curl kalix-web-testing.default.svc.cluster.local
curl : Unable to connect to the remote server

PS C:\app> tracert 10.0.236.124

Tracing route to kalix-web-testing.default.svc.cluster.local [10.0.236.124]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  kalix-web-testing.default.svc.cluster.local [10.0.236.124]

Trace complete.

PS C:\app> curl 10.0.236.124
curl : Unable to connect to the remote server
```

Here is the `ipconfig /all` from within the windows pod

```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : 3c23eedd86b7
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : tb5sk3o5ejfetd4bcvwwq1ythb.dx.internal.cloudapp.net

Ethernet adapter vEthernet (Container NIC a6bfd8cc):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #5
   Physical Address. . . . . . . . . : 00-15-5D-33-5E-AF
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::3dbf:6863:c3d9:a1b9%33(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.244.2.250(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Container NIC eac57e13):

   Connection-specific DNS Suffix  . : tb5sk3o5ejfetd4bcvwwq1ythb.dx.internal.cloudapp.net
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #6
   Physical Address. . . . . . . . . : 00-15-5D-21-9C-43
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::adda:bfb8:594e:3f84%37(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.28.138.27(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.28.128.1
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Disabled
```

Here is a dump of `netsh advf show allprofiles` after RDP into the node. Interestingly it looks like the public profile state is not ON! However it looks like the firewall is completely off?

```
PS C:\Users\kalixhealth> netsh advf show allprofiles

Domain Profile Settings:
----------------------------------------------------------------------
State                                 OFF
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Disable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096


Private Profile Settings:
----------------------------------------------------------------------
State                                 OFF
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Disable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096


Public Profile Settings:
----------------------------------------------------------------------
State                                 OFF
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Disable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096

Ok.
```

![image](https://cloud.githubusercontent.com/assets/1185777/25768430/b3f462c2-31b8-11e7-9199-604c57d498e5.png)

If I enable the firewall I am not able to access the site externally (via the ingress) or internally (using `kubectl exec`).

Does that mean that the firewall is not being setup properly?

I will try a kubernetes 1.5.3 cluster now.

**Comment by JiangtianLi** [comment]
@ajorkowski All your settings looks right to me. DNS server is set correctly and `Resolve-DnsName` works as expected. The public profile of firewall should be OFF. Sometimes after you RDP to the Windows node, it might be turned ON. But OFF is expected. 

Are you able to `curl kalix-web-testing.default.svc.cluster.local` in the kalix-web-testing container itself? Which port is it using?

**Comment by ajorkowski** [comment]
Sorry, took a while to get the next cluster up. I can confirm that the same problem is happening in kubernetes 1.5.3.

Something else I noticed was that while my container was spinning up I did get:

```
PS C:\app> curl kalix-web-testing.default.svc.cluster.local
curl : The underlying connection was closed: An unexpected error occurred on a receive.
```

So it seems that the curl is reaching the endpoint in this situation? As soon as the health endpoint is reporting active (ie IIS is running) the `Unable to connect to the remote server` error resumes.

Ok, next, I logged into the `kalix-web-testing` container and I'm getting the same issue. 

```
PS C:\install> Resolve-DnsName kalix-web-testing.default.svc.cluster.local

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
kalix-web-testing.default.svc.cluster.local    A      30    Answer     10.0.131.27

PS C:\install> curl kalix-web-testing.default.svc.cluster.local
curl : Unable to connect to the remote server
```

That's pretty strange... If I RDP into the node I am able to hit the website (just to prove it is really serving!).

```
PS C:\Users\kalixhealth> docker container list
CONTAINER ID        IMAGE                                COMMAND                   CREATED             STATUS              PORTS               NAMES
3c214850587a        kalixinc/kalix-web:testing.1.1.100   "C:\\ServiceMonitor..."   22 minutes ago      Up 21 minutes       80/tcp, 443/tcp     k8s_kalix-web-testing.18286b66_kalix-web-testing-1157895259-1fbl7_default_485991fa-31ff-11e7-b650-000d3a366294_e4d932bb
bc4db34c74e4        kubletwin/pause                      "cmd /S /C 'powers..."    33 minutes ago      Up 33 minutes                           k8s_POD.98d1fab0_kalix-web-testing-1157895259-1fbl7_default_485991fa-31ff-11e7-b650-000d3a366294_504803b5

PS C:\Users\kalixhealth> docker inspect --format '{{ .NetworkSettings.Networks.nat.IPAddress }}' 3c214850587a
172.27.176.217


PS C:\Users\kalixhealth> curl 172.27.176.217

StatusCode        : 200
StatusDescription : OK
```

Interestingly, in my deployment file I only specify port 80, but it looks like it is exposing both 80 and 443 (the base docker container that I am using specify both ports, but I am not using 443). Internally IIS is also using 80, so it is an 80 -> 80 port mapping in docker.

**Comment by ajorkowski** [comment]
If I go back into the pod the IP address on one of the NICs matches `172.27.176.217` above, but I get the same issue if I try to curl it directly:

```
PS C:\install> curl 172.27.176.217
curl : Unable to connect to the remote server

PS C:\install> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : 3c214850587a
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : q3kjqfg4z4zubi0nieiwfoho3h.dx.internal.cloudapp.net

Ethernet adapter vEthernet (Container NIC 8b77494d):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #5
   Physical Address. . . . . . . . . : 00-15-5D-FA-83-0C
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::2c09:ecd8:131d:b11f%33(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.244.2.18(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Container NIC 9105bb39):

   Connection-specific DNS Suffix  . : q3kjqfg4z4zubi0nieiwfoho3h.dx.internal.cloudapp.net
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #6
   Physical Address. . . . . . . . . : 00-15-5D-4C-0C-78
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::9dbe:88dc:24cb:9486%37(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.27.176.217(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.27.176.1
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Disabled
```

**Comment by ajorkowski** [comment]
I can also confirm that if RDPed into the node that the resolved IP address via the DNS `10.0.131.27` also works.

```
PS C:\Users\kalixhealth> curl 10.0.131.27

StatusCode        : 200
StatusDescription : OK
```

**Comment by ajorkowski** [comment]
Oh man... so dumb :( I gave this another go today and luckily I got the DNS name resolution issue at the same time as testing the curl:

```
PS C:\app> curl kalix-web-testing.default.svc.cluster.local
curl : The remote name could not be resolved: 'testapp.kalixhealth.com'
```

This led me to work out what the issue is... The first hit to the app (via the internal call) is working, but returning a redirect, and the redirect is for the external domain, which is the one that times out. 

```
PS C:\app> Invoke-WebRequest -Uri "kalix-web-testing.default.svc.cluster.local" -MaximumRedirection 0 -UseBasicParsing

StatusCode        : 302
StatusDescription : Found
```

So basically this issue can be distilled to access to external ip address does not work from inside the cluster. ie From outside the cluster I can access `test.kalixhealth.com`, while inside the PODS (It can be accessed from the nodes) I cannot:

```
PS C:\app> Resolve-DnsName test.kalixhealth.com

Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
test.kalixhealth.com           CNAME  3113  Answer     cluster.kalix.co

Name       : cluster.kalix.co
QueryType  : A
TTL        : 3113
Section    : Answer
IP4Address : 13.93.219.64

PS C:\app> ping 13.93.219.64

Pinging 13.93.219.64 with 32 bytes of data:
Request timed out.

PS C:\app> curl 13.93.219.64
curl : Unable to connect to the remote server
```

I believe this is an issue that might already be tracked somewhere else, I am sorry for wasting your time a bit! I have to be very careful internally in my app that I am not trying to access something that resolves to the external ip, or will redirect to the external ip!

**Comment by JiangtianLi** [comment]
@ajorkowski Good findings. I see, redirect is the culprit here.

**Comment by minherz** [comment]
I experience a similar issue of failing to resolve another service address via hostname: `<service-name>.<namespace>.svc.cluster.local` with similar output by `ipconfig /all`.
It seems the resolving depends which NIC the request hits. If it hits one that has DNS: 10.0.0.10 then everything is working. If it hits another which has a list of DNS addresses in a form of `fec0:0:0:ffff::n%1` then it fails. Appreciate any advise.

**Comment by JiangtianLi** [comment]
@minherz The DNS issue with the correct have been fixed for one month now. How and when did you deploy your k8s windows cluster?

**Comment by minherz** [comment]
@JiangtianLi  We created a deployment configuration and generated a deploy template using `acs-engine` and then launch it using `ansible`. `ansible` implements a module which implements acs deployment api

**Comment by JiangtianLi** [comment]
@minherz Does it consistently pick the incorrect NIC for DNS query in the same container? What is the output of `Get-NetAdapter` in the container?

**Comment by minherz** [comment]
I do not know how to direct a request to the "right" NIC. However, each deployment that we did resulted in inaccessible service. Eventually, we moved to use Kubernetes induced environment variables. However, we prefer to do it "old" way. I cannot compare the behavior with one of the ACS since it is impossible to create Kubernetes ACS instance right now (there is a problem with missing windows image).
